### PR TITLE
Facet plot for proportion with median > 1

### PR DESCRIPTION
**Pull request by seabbs**
This PR adds a facet region version of the proportion of UTLAs > 1. Really liking the overall plot as a summary of what is happening and thought a regional version would be handy.

It also: 

- adds `renv` for soem dependencies management.
- Switchess to using `renv` in the GitHub action.
- Adds a docker container and vscode fluff (very optional but handy for me)

### CODE REVIEW

**Comment by seabbs** [comment]
Checked github action is working though it looks like caching is not.

**Review by sbfnk — CHANGES_REQUESTED** [review]
Thanks! What's the stuff in `.devcontainer` and `renv` for? Are these standard scripts or did you write them?

On the plot, I like the idea of resolving this by region but I'm not yet convinced this is the best way of displaying it - the different denominators by region makes the comparison a bit difficult to interpret, I think.

As an alternative, how about colouring the bars in the non-faceted plot by region?

**Comment by seabbs** [comment]
.devcontainer is docker and vs related stuff so you can build the dev environment automatically from vscode (or using docker somewhere else). renv are automated scripts from the renv package for dependency management. It is like packrat but less rubbish. When someone opens this repo though scripts kick in and bootstrap the environment to be as specified (like a less good virtual environment in python)

**Comment by seabbs** [comment]
I don't typically find much value in stacked bar charts but will have a look.

**Pull request merged**
